----------------------------------------------------------------
--                                                            --
--           GIVEAWAYS SECURITY ENHANCEMENTS                  --
--                                                            --
----------------------------------------------------------------

-- Add Turnstile verification tracking
ALTER TABLE giveaway_participants
ADD COLUMN IF NOT EXISTS turnstile_token TEXT,
ADD COLUMN IF NOT EXISTS turnstile_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS verification_ip INET;

-- Add telegram handle validation
ALTER TABLE giveaway_participants
ADD COLUMN IF NOT EXISTS telegram_handle TEXT;

-- Create index for telegram handle lookups
CREATE INDEX IF NOT EXISTS giveaway_participants_telegram_idx 
ON giveaway_participants(telegram_handle) 
WHERE telegram_handle IS NOT NULL;

-- Update giveaway status enum to include 'running'
ALTER TABLE giveaways DROP CONSTRAINT IF EXISTS giveaways_status_check;
ALTER TABLE giveaways ADD CONSTRAINT giveaways_status_check 
CHECK (status IN ('active', 'running', 'ended', 'cancelled'));

COMMENT ON COLUMN giveaways.status IS 'active (scheduled), running (live), ended, cancelled';

-- Add verification attempts tracking
CREATE TABLE IF NOT EXISTS verification_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Tracking
  ip_address INET NOT NULL,
  fingerprint TEXT,
  action TEXT NOT NULL,
  
  -- Turnstile
  turnstile_token TEXT,
  turnstile_success BOOLEAN DEFAULT FALSE,
  
  -- Result
  success BOOLEAN DEFAULT FALSE,
  error_message TEXT,
  
  -- Metadata
  user_agent TEXT,
  giveaway_id BIGINT REFERENCES giveaways(id) ON DELETE CASCADE
);

-- Indexes for verification attempts
CREATE INDEX IF NOT EXISTS verification_attempts_ip_idx ON verification_attempts(ip_address, created_at);
CREATE INDEX IF NOT EXISTS verification_attempts_fingerprint_idx ON verification_attempts(fingerprint, created_at);
CREATE INDEX IF NOT EXISTS verification_attempts_giveaway_idx ON verification_attempts(giveaway_id);

-- Cleanup old verification attempts (keep for 7 days)
CREATE INDEX IF NOT EXISTS verification_attempts_cleanup_idx ON verification_attempts(created_at) 
WHERE created_at < NOW() - INTERVAL '7 days';

----------------------------------------------------------------
--                  ENHANCED FUNCTIONS                        --
----------------------------------------------------------------

-- Enhanced join giveaway with Turnstile verification
CREATE OR REPLACE FUNCTION join_giveaway_secure(
  p_giveaway_id BIGINT,
  p_telegram_handle TEXT,
  p_guest_name TEXT,
  p_ip_address INET,
  p_fingerprint TEXT,
  p_turnstile_token TEXT,
  p_user_agent TEXT DEFAULT NULL
)
RETURNS JSON
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_giveaway RECORD;
  v_identifier TEXT;
  v_participant_count INTEGER;
  v_ip_count INTEGER;
  v_telegram_count INTEGER;
  v_fingerprint_count INTEGER;
  v_guest_id UUID;
BEGIN
  -- Validate inputs
  IF p_telegram_handle IS NULL OR p_telegram_handle = '' THEN
    RETURN json_build_object('success', FALSE, 'error', 'Telegram handle is required');
  END IF;
  
  IF p_guest_name IS NULL OR p_guest_name = '' THEN
    RETURN json_build_object('success', FALSE, 'error', 'Name is required');
  END IF;
  
  -- Normalize telegram handle
  p_telegram_handle := LOWER(TRIM(BOTH FROM p_telegram_handle));
  IF NOT p_telegram_handle ~ '^@?[a-z0-9_]{5,32}$' THEN
    RETURN json_build_object('success', FALSE, 'error', 'Invalid Telegram handle format. Use @username (5-32 characters)');
  END IF;
  
  -- Ensure @ prefix
  IF NOT p_telegram_handle LIKE '@%' THEN
    p_telegram_handle := '@' || p_telegram_handle;
  END IF;
  
  -- Get giveaway details
  SELECT * INTO v_giveaway
  FROM giveaways
  WHERE id = p_giveaway_id
  AND deleted_at IS NULL
  FOR UPDATE;
  
  -- Validation checks
  IF NOT FOUND THEN
    RETURN json_build_object('success', FALSE, 'error', 'Giveaway not found');
  END IF;
  
  IF v_giveaway.status NOT IN ('active', 'running') THEN
    RETURN json_build_object('success', FALSE, 'error', 'Giveaway is not active');
  END IF;
  
  IF v_giveaway.is_banned THEN
    RETURN json_build_object('success', FALSE, 'error', 'This giveaway has been suspended');
  END IF;
  
  IF v_giveaway.end_date < NOW() THEN
    RETURN json_build_object('success', FALSE, 'error', 'Giveaway has ended');
  END IF;
  
  -- Check max participants
  IF v_giveaway.max_participants IS NOT NULL THEN
    SELECT COUNT(*) INTO v_participant_count
    FROM giveaway_participants
    WHERE giveaway_id = p_giveaway_id;
    
    IF v_participant_count >= v_giveaway.max_participants THEN
      RETURN json_build_object('success', FALSE, 'error', 'Giveaway is full. Maximum participants reached.');
    END IF;
  END IF;
  
  -- Rate limiting by IP
  v_identifier := p_ip_address::TEXT;
  IF NOT check_rate_limit(v_identifier, 'giveaway_join', 10, 60) THEN
    RETURN json_build_object('success', FALSE, 'error', 'Too many attempts. Please wait before trying again.');
  END IF;
  
  -- Check IP abuse (max 3 entries per IP per giveaway)
  SELECT COUNT(*) INTO v_ip_count
  FROM giveaway_participants
  WHERE giveaway_id = p_giveaway_id AND ip_address = p_ip_address;
  
  IF v_ip_count >= 3 THEN
    RETURN json_build_object('success', FALSE, 'error', 'Maximum entries reached from your connection');
  END IF;
  
  -- Check fingerprint abuse (max 2 entries per fingerprint per giveaway)
  SELECT COUNT(*) INTO v_fingerprint_count
  FROM giveaway_participants
  WHERE giveaway_id = p_giveaway_id AND fingerprint = p_fingerprint;
  
  IF v_fingerprint_count >= 2 THEN
    RETURN json_build_object('success', FALSE, 'error', 'You have already participated in this giveaway');
  END IF;
  
  -- Check telegram handle (must be unique per giveaway)
  SELECT COUNT(*) INTO v_telegram_count
  FROM giveaway_participants
  WHERE giveaway_id = p_giveaway_id AND telegram_handle = p_telegram_handle;
  
  IF v_telegram_count > 0 THEN
    RETURN json_build_object('success', FALSE, 'error', 'This Telegram handle has already participated');
  END IF;
  
  -- Generate guest ID
  v_guest_id := gen_random_uuid();
  
  -- Insert participant
  INSERT INTO giveaway_participants (
    giveaway_id, guest_id, guest_name, telegram_handle,
    ip_address, user_agent, fingerprint, weight,
    turnstile_token, turnstile_verified, verification_ip
  ) VALUES (
    p_giveaway_id, v_guest_id, p_guest_name, p_telegram_handle,
    p_ip_address, p_user_agent, p_fingerprint, 1,
    p_turnstile_token, TRUE, p_ip_address
  );
  
  -- Log verification attempt
  INSERT INTO verification_attempts (
    ip_address, fingerprint, action, turnstile_token,
    turnstile_success, success, giveaway_id, user_agent
  ) VALUES (
    p_ip_address, p_fingerprint, 'join_giveaway', p_turnstile_token,
    TRUE, TRUE, p_giveaway_id, p_user_agent
  );
  
  RETURN json_build_object(
    'success', TRUE, 
    'message', 'Successfully joined the giveaway!',
    'participant_id', v_guest_id
  );
  
EXCEPTION
  WHEN unique_violation THEN
    -- Log failed attempt
    INSERT INTO verification_attempts (
      ip_address, fingerprint, action, success, error_message, giveaway_id
    ) VALUES (
      p_ip_address, p_fingerprint, 'join_giveaway', FALSE, 'Already participated', p_giveaway_id
    );
    RETURN json_build_object('success', FALSE, 'error', 'You have already participated in this giveaway');
  WHEN OTHERS THEN
    -- Log error
    INSERT INTO verification_attempts (
      ip_address, fingerprint, action, success, error_message, giveaway_id
    ) VALUES (
      p_ip_address, p_fingerprint, 'join_giveaway', FALSE, SQLERRM, p_giveaway_id
    );
    RETURN json_build_object('success', FALSE, 'error', 'An error occurred. Please try again.');
END;
$$ LANGUAGE plpgsql;

----------------------------------------------------------------

-- Function to check if user already participated
CREATE OR REPLACE FUNCTION check_participation(
  p_giveaway_id BIGINT,
  p_telegram_handle TEXT DEFAULT NULL,
  p_fingerprint TEXT DEFAULT NULL,
  p_ip_address INET DEFAULT NULL
)
RETURNS JSON
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_participated BOOLEAN := FALSE;
  v_method TEXT;
BEGIN
  -- Normalize telegram handle
  IF p_telegram_handle IS NOT NULL THEN
    p_telegram_handle := LOWER(TRIM(BOTH FROM p_telegram_handle));
    IF NOT p_telegram_handle LIKE '@%' THEN
      p_telegram_handle := '@' || p_telegram_handle;
    END IF;
  END IF;
  
  -- Check by telegram handle (most reliable)
  IF p_telegram_handle IS NOT NULL THEN
    SELECT EXISTS(
      SELECT 1 FROM giveaway_participants
      WHERE giveaway_id = p_giveaway_id 
      AND telegram_handle = p_telegram_handle
    ) INTO v_participated;
    
    IF v_participated THEN
      RETURN json_build_object(
        'participated', TRUE, 
        'method', 'telegram',
        'message', 'You have already participated with this Telegram handle'
      );
    END IF;
  END IF;
  
  -- Check by fingerprint
  IF p_fingerprint IS NOT NULL THEN
    SELECT EXISTS(
      SELECT 1 FROM giveaway_participants
      WHERE giveaway_id = p_giveaway_id 
      AND fingerprint = p_fingerprint
    ) INTO v_participated;
    
    IF v_participated THEN
      RETURN json_build_object(
        'participated', TRUE, 
        'method', 'device',
        'message', 'You have already participated from this device'
      );
    END IF;
  END IF;
  
  -- Check by IP (less reliable, just for info)
  IF p_ip_address IS NOT NULL THEN
    SELECT EXISTS(
      SELECT 1 FROM giveaway_participants
      WHERE giveaway_id = p_giveaway_id 
      AND ip_address = p_ip_address
    ) INTO v_participated;
    
    IF v_participated THEN
      RETURN json_build_object(
        'participated', TRUE, 
        'method', 'ip',
        'message', 'Someone has already participated from your connection'
      );
    END IF;
  END IF;
  
  RETURN json_build_object('participated', FALSE);
END;
$$ LANGUAGE plpgsql;

----------------------------------------------------------------

-- Cleanup function for old verification attempts
CREATE OR REPLACE FUNCTION cleanup_old_verification_attempts()
RETURNS VOID
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  DELETE FROM verification_attempts
  WHERE created_at < NOW() - INTERVAL '7 days';
END;
$$ LANGUAGE plpgsql;

----------------------------------------------------------------
--                     GRANTS                                 --
----------------------------------------------------------------

-- Grant execute permissions
GRANT EXECUTE ON FUNCTION join_giveaway_secure TO authenticated, anon;
GRANT EXECUTE ON FUNCTION check_participation TO authenticated, anon;
GRANT EXECUTE ON FUNCTION cleanup_old_verification_attempts TO authenticated;

